name: "killer"

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cancel running jobs for merged PRs
        uses: Itxaka/CancelRunningJobs@v1.0.0